version: '3.8'

services:
  # Matrix Synapse homeserver with SQLite
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: mycelium-synapse
    restart: unless-stopped
    network_mode: host
    volumes:
      - synapse_data:/data
      - ./synapse-init.sh:/synapse-init.sh
    environment:
      SYNAPSE_SERVER_NAME: localhost
      SYNAPSE_REPORT_STATS: "no"
    entrypoint: ["/synapse-init.sh"]

  # Element Web Client
  element:
    image: vectorim/element-web:latest
    container_name: mycelium-element
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./element-config.json:/app/config.json
    depends_on:
      - synapse

  # Mock Bridge Service (placeholder)
  bridge-mock:
    image: nginx:alpine
    container_name: mycelium-bridge-mock
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./mock-bridge:/usr/share/nginx/html
    command: >
      sh -c "
        echo '{\"status\":\"healthy\",\"service\":\"bridge-mock\",\"version\":\"dev\"}' > /usr/share/nginx/html/health &&
        nginx -g 'daemon off;'
      "

  # Mock Discovery Service (placeholder)
  discovery-mock:
    image: nginx:alpine
    container_name: mycelium-discovery-mock
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./mock-discovery:/usr/share/nginx/html
    command: >
      sh -c "
        echo '{\"servers\":[{\"name\":\"localhost\",\"status\":\"active\"}],\"total\":1}' > /usr/share/nginx/html/servers &&
        echo '{\"status\":\"healthy\",\"service\":\"discovery-mock\",\"version\":\"dev\"}' > /usr/share/nginx/html/health &&
        nginx -g 'daemon off;'
      "

volumes:
  synapse_data:
