name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Create environment file
        run: |
          cd web
          echo "VITE_APP_DOMAIN=${{ secrets.VITE_APP_DOMAIN }}" > .env
          echo "VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}" >> .env
          echo "VITE_TF_CONNECT_APPID=${{ secrets.VITE_TF_CONNECT_APPID }}" >> .env
          echo "VITE_TF_CONNECT_PUBLICKEY=${{ secrets.VITE_TF_CONNECT_PUBLICKEY }}" >> .env
          echo "VITE_CALLBACK_URL=${{ secrets.VITE_CALLBACK_URL }}" >> .env
          echo "VITE_MYCELIUM_API_URL=${{ secrets.VITE_MYCELIUM_API_URL }}" >> .env
          echo "VITE_DEMO_MODE=${{ secrets.VITE_DEMO_MODE }}" >> .env
          echo "VITE_DEBUG_LOGGING=${{ secrets.VITE_DEBUG_LOGGING }}" >> .env
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env

      - name: Build
        run: |
          cd web
          npm run build

      - name: Create CNAME file for custom domain
        run: |
          if [ ! -z "${{ secrets.VITE_APP_DOMAIN }}" ] && [ "${{ secrets.VITE_APP_DOMAIN }}" != "localhost" ]; then
            echo "${{ secrets.VITE_APP_DOMAIN }}" > web/dist/CNAME
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
