name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Create environment file
        run: |
          cd web
          echo "VITE_APP_DOMAIN=${{ secrets.VITE_APP_DOMAIN }}" > .env
          echo "VITE_APP_NAME=Mycelium Chat" >> .env
          echo "VITE_TF_CONNECT_APPID=${{ secrets.VITE_APP_DOMAIN }}" >> .env
          echo "VITE_TF_CONNECT_PUBLICKEY=WhBv5majL0aNLsTqsvlRSBBiScAeOYVs1gbtX55AQCI=" >> .env
          echo "VITE_CALLBACK_URL=/callback.html" >> .env
          echo "VITE_MYCELIUM_API_URL=http://localhost:8989" >> .env
          echo "VITE_DEMO_MODE=false" >> .env
          echo "VITE_DEBUG_LOGGING=false" >> .env
          echo "VITE_BASE_URL=/" >> .env

      - name: Build
        run: |
          cd web
          npm run build
          echo "Files in dist after build:"
          ls -la dist/
          echo "Checking callback.html exists:"
          test -f dist/callback.html && echo "✅ callback.html found" || echo "❌ callback.html missing"
          echo "Looking for callback.html:"
          find . -name "callback.html" -type f
          echo "Manually copying callback.html to dist:"
          if [ -f public/callback.html ]; then
            cp public/callback.html dist/callback.html
          elif [ -f ../public/callback.html ]; then
            cp ../public/callback.html dist/callback.html
          else
            echo "callback.html not found, creating from src:"
            cp src/callback.html dist/callback.html
          fi
          echo "✅ callback.html copied to dist/"

      - name: Create CNAME file for custom domain
        run: |
          if [ ! -z "${{ secrets.VITE_APP_DOMAIN }}" ] && [ "${{ secrets.VITE_APP_DOMAIN }}" != "localhost" ]; then
            echo "${{ secrets.VITE_APP_DOMAIN }}" > web/dist/CNAME
          fi

      - name: Debug dist contents before upload
        run: |
          echo "Contents of web/dist before upload:"
          find web/dist -type f -exec ls -la {} \;
          echo "Total files: $(find web/dist -type f | wc -l)"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
